# Simplified schema - only essential fields
id: "python-fullstack-marketplace"
name: "Digital Marketplace" 
generators:
  - name: workspace
  - name: base-contracts-python
  - name: create-smart-contract
    data:
      language: python
      contract_name: "digital_marketplace"
  - name: base-frontend-react
  - name: example-digital-marketplace
  - name: testing
  - name: linting
  - name: devcontainer