id = "python-fullstack-marketplace"
name = "Digital Marketplace"

[[generators]]
name = "workspace"

[[generators]]
name = "base-contracts-python"

[[generators]]
name = "create-smart-contract"
[generators.data]
language = "python"
contract_name = "digital_marketplace"

[[generators]]
name = "base-frontend-react"

[[generators]]
name = "example-digital-marketplace"

[[generators]]
name = "testing"

[[generators]]
name = "linting"

[[generators]]
name = "devcontainer"