[algokit]
min_version = "v2.0.0"

[project]
type = "frontend"
name = 'typescript-hello-world'
artifacts = "src/contracts"

[project.run]
build = { commands = ['npm run build'], description = 'Build frontend' }
